version: 2
jobs:
  build:
    working_directory: ~/tmp
    dependencies:
      pre:
        - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome.deb
        - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
        - rm google-chrome.deb
    docker:
      - image: circleci/node:7
     - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - run: yarn install
      - run: npm run-script ng build
      - run: npm run-script ng lint
      - run: npm run-script ng test
      - run: npm run-script ng e2e
