version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: yarn install
      - run: npm run-script ng build
      - run: npm run-script ng test
      - run: npm run-script ng lint
      - run: npm run-script ng e2e
